name: docker-arm
on: [push]
env:
  REPO_DIR: /home/Cropbox.jl
  IMAGE_NAME: cropbox/cropbox-arm
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: easimon/maximize-build-space@v6
        with:
          overprovision-lvm: 'true'
          remove-dotnet: 'true'
          remove-android: 'true'
      - uses: actions/checkout@v3
      - uses: rlespinasse/github-slug-action@v4
      - uses: docker/metadata-action@v4
        with:
          images: ${{ env.IMAGE_NAME }}
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v4
        with:
          context: .
          file: .binder/Dockerfile
          build-args: REPO_DIR=${{ env.REPO_DIR}}
          platforms: linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=image,name=${{ env.IMAGE_NAME }},push-by-digest=true,name-canonical=true,push=true
